export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const VALIDATE_USER = 'VALIDATE_USER';

export const REQUEST_API_DATA = 'REQUEST_API_DATA';
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA';